import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { spawn } from "node:child_process";
import { parseProxyPort } from "./ports.js";
import { buildHeaders } from "./mihomo.js";

const RELEASE_API = "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest";

export function embeddedMihomoPaths(config = {}, homeDir = homedir()) {
  const binaryPath = expandHomeLike(config.binaryPath || "~/Library/Application Support/MD-Browser/bin/mihomo", homeDir);
  const configPath = expandHomeLike(config.configPath || "~/Library/Application Support/MD-Browser/mihomo/config.yaml", homeDir);
  const workDir = dirname(configPath);
  return {
    binaryPath,
    configPath,
    workDir,
    pidPath: join(workDir, "mihomo.pid")
  };
}

export async function embeddedMihomoStatus(config = {}, { homeDir = homedir(), fetchImpl = fetch, isProcessRunningImpl = isProcessRunning } = {}) {
  const paths = embeddedMihomoPaths(config, homeDir);
  const installed = existsSync(paths.binaryPath);
  const configExists = existsSync(paths.configPath);
  const pid = readPid(paths.pidPath);
  const processRunning = Boolean(pid && isProcessRunningImpl(pid));
  const stalePidCleared = Boolean(pid && !processRunning);
  if (stalePidCleared) {
    rmSync(paths.pidPath, { force: true });
  }
  let apiConnected = false;
  let version = "";
  let apiError = "";

  try {
    const response = await fetchImpl(`${baseUrl(config)}/version`, {
      headers: buildHeaders(config),
      signal: AbortSignal.timeout(1500)
    });
    apiConnected = Boolean(response.ok);
    if (apiConnected && typeof response.json === "function") {
      const data = await response.json();
      version = data.version || data.Version || "";
    }
  } catch (error) {
    apiError = error.message;
  }

  return {
    installed,
    configExists,
    processRunning,
    apiConnected,
    version,
    apiError,
    stalePidCleared,
    paths
  };
}

export function buildEmbeddedMihomoConfig(config = {}, routeEntries = []) {
  const controller = new URL(config.controllerUrl || "http://127.0.0.1:19090");
  const host = controller.hostname || "127.0.0.1";
  const port = controller.port || "19090";
  const subscriptionUrl = String(config.subscriptionUrl || "").trim();
  if (!subscriptionUrl) {
    throw new Error("内置 Mihomo 需要先配置订阅地址。");
  }
  const listeners = routeEntries
    .map((route) => ({
      name: route.label || route.key || `md-${parseProxyPort(route.proxyUrl)}`,
      port: parseProxyPort(route.proxyUrl),
      proxy: route.nodeName || route.mihomoGroup || ""
    }))
    .filter((route) => Number.isInteger(route.port) && route.proxy);
  const routeGroups = listeners.map((listener) => ({
    name: embeddedRouteGroupName(listener),
    proxy: listener.proxy
  }));

  return [
    "# Generated by MD-Browser. Edit in the app instead of changing this file manually.",
    "allow-lan: false",
    "mode: rule",
    "log-level: info",
    `external-controller: ${host}:${port}`,
    `secret: ${quoteYamlString(config.secret || "")}`,
    "",
    "proxy-providers:",
    "  md-browser-subscription:",
    "    type: http",
    `    url: ${quoteYamlString(subscriptionUrl)}`,
    "    path: ./subscription.yaml",
    "    interval: 3600",
    "    health-check:",
    "      enable: true",
    "      url: https://www.gstatic.com/generate_204",
    "      interval: 300",
    "",
    "proxy-groups:",
    "  - name: MD-Browser",
    "    type: select",
    "    use:",
    "      - md-browser-subscription",
    ...routeGroups.flatMap((group) => [
      `  - name: ${quoteYamlString(group.name)}`,
      "    type: select",
      ...(isBuiltInProxy(group.proxy) ? [
        "    proxies:",
        `      - ${quoteYamlString(group.proxy)}`
      ] : [
        "    use:",
        "      - md-browser-subscription",
        `    filter: ${quoteYamlString(`^${escapeRegexLiteral(group.proxy)}$`)}`
      ])
    ]),
    "",
    "listeners:",
    ...listeners.flatMap((listener) => [
      `  - name: ${quoteYamlString(listener.name)}`,
      "    type: mixed",
      "    listen: 127.0.0.1",
      `    port: ${listener.port}`,
      `    proxy: ${quoteYamlString(embeddedRouteGroupName(listener))}`,
      "    udp: true"
    ]),
    "",
    "rules:",
    "  - MATCH,MD-Browser",
    ""
  ].join("\n");
}

export function embeddedRouteGroupName(route) {
  const port = Number.isInteger(route.port) ? route.port : parseProxyPort(route.proxyUrl);
  return `MD-Browser-${port}`;
}

export function writeEmbeddedMihomoConfig(config = {}, routeEntries = [], { homeDir = homedir() } = {}) {
  const paths = embeddedMihomoPaths(config, homeDir);
  mkdirSync(paths.workDir, { recursive: true });
  const content = buildEmbeddedMihomoConfig(config, routeEntries);
  writeFileSync(paths.configPath, content);
  return { configPath: paths.configPath, written: true };
}

export async function resolveLatestMihomoAsset({ fetchImpl = fetch, platform = process.platform, arch = process.arch } = {}) {
  const response = await fetchImpl(RELEASE_API, {
    headers: { accept: "application/vnd.github+json", "user-agent": "MD-Browser" },
    signal: AbortSignal.timeout(10000)
  });
  if (!response.ok) throw new Error(`Mihomo release lookup failed: ${response.status}`);
  const release = await response.json();
  return selectMihomoReleaseAsset(release, { platform, arch });
}

export function selectMihomoReleaseAsset(release, { platform = process.platform, arch = process.arch } = {}) {
  const normalizedArch = arch === "x64" ? "amd64" : arch;
  const assets = Array.isArray(release?.assets) ? release.assets : [];
  const version = release?.tag_name ? String(release.tag_name).replace(/^v/i, "") : "";
  const matches = assets
    .filter((asset) => {
      const name = String(asset.name || "").toLowerCase();
      return name.startsWith("mihomo-")
      && name.includes(`-${platform}-`)
      && name.includes(`-${normalizedArch}-`)
      && name.endsWith(".gz")
      && asset.browser_download_url;
    })
    .sort((left, right) => mihomoAssetRank(left.name, { platform, arch: normalizedArch, version }) - mihomoAssetRank(right.name, { platform, arch: normalizedArch, version }));
  const match = matches[0];
  if (!match) {
    throw new Error(`未找到适合 ${platform}/${arch} 的 Mihomo 二进制。`);
  }
  return {
    version: release.tag_name || "",
    name: match.name,
    url: match.browser_download_url
  };
}

function mihomoAssetRank(name, { platform, arch, version = "" } = {}) {
  const lower = String(name || "").toLowerCase();
  if (version && lower === `mihomo-${platform}-${arch}-v${version}.gz`) return 0;
  if (lower.includes("-go124-")) return 1;
  if (lower.includes("-go123-")) return 2;
  if (lower.includes("-go122-")) return 3;
  if (lower.includes("-go121-")) return 4;
  if (lower.includes("-go120-")) return 5;
  if (lower.includes("-compatible-")) return 20;
  return 10;
}

export async function installEmbeddedMihomo(config = {}, { homeDir = homedir(), fetchImpl = fetch } = {}) {
  const asset = await resolveLatestMihomoAsset({ fetchImpl });
  const response = await fetchImpl(asset.url, { signal: AbortSignal.timeout(120000) });
  if (!response.ok) throw new Error(`Mihomo download failed: ${response.status}`);
  const buffer = Buffer.from(await response.arrayBuffer());
  const binary = gunzipSync(buffer);
  const paths = embeddedMihomoPaths(config, homeDir);
  mkdirSync(dirname(paths.binaryPath), { recursive: true });
  writeFileSync(paths.binaryPath, binary);
  chmodSync(paths.binaryPath, 0o755);
  return { installed: true, asset, binaryPath: paths.binaryPath };
}

export function startEmbeddedMihomo(config = {}, { homeDir = homedir(), routes = [], spawnImpl = spawn, isProcessRunningImpl = isProcessRunning } = {}) {
  const paths = embeddedMihomoPaths(config, homeDir);
  const existingPid = readPid(paths.pidPath);
  if (existingPid && isProcessRunningImpl(existingPid)) {
    return { started: false, alreadyRunning: true, pid: existingPid, configPath: paths.configPath };
  }
  if (existingPid) rmSync(paths.pidPath, { force: true });
  if (!existsSync(paths.binaryPath)) throw new Error("内置 Mihomo Core 尚未安装。");
  writeEmbeddedMihomoConfig(config, routes, { homeDir });
  const child = spawnImpl(paths.binaryPath, ["-f", paths.configPath], {
    cwd: paths.workDir,
    detached: true,
    stdio: "ignore"
  });
  child.unref();
  writeFileSync(paths.pidPath, String(child.pid));
  return { started: true, pid: child.pid, configPath: paths.configPath };
}

export function stopEmbeddedMihomo(config = {}, { homeDir = homedir(), killImpl = process.kill } = {}) {
  const paths = embeddedMihomoPaths(config, homeDir);
  const pid = readPid(paths.pidPath);
  if (!pid) return { stopped: false, reason: "not-running" };
  try {
    killImpl(pid);
  } catch (error) {
    if (error.code !== "ESRCH") throw error;
  }
  rmSync(paths.pidPath, { force: true });
  return { stopped: true, pid };
}

function readPid(pidPath) {
  try {
    const value = Number(readFileSync(pidPath, "utf8").trim());
    return Number.isInteger(value) && value > 0 ? value : 0;
  } catch {
    return 0;
  }
}

function isProcessRunning(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function expandHomeLike(path, homeDir) {
  return String(path || "").startsWith("~/") ? join(homeDir, String(path).slice(2)) : String(path || "");
}

function baseUrl(config) {
  return String(config.controllerUrl || "http://127.0.0.1:19090").replace(/\/$/, "");
}

function quoteYamlString(value) {
  return `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function escapeRegexLiteral(value) {
  return String(value).replace(/[\\^$.*+?()[\]{}|]/g, "\\$&");
}

function isBuiltInProxy(value) {
  return ["DIRECT", "REJECT", "REJECT-DROP", "PASS", "PASS-RULE", "COMPATIBLE"].includes(String(value || ""));
}
